development:
  adapter: postgresql
  encoding: utf8
  database: distracker_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: distracker_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: distracker_production
  pool: 5
  password: